### ISSUE TITLE
Research fields - removing one after adding the max number doesn't give you the add button again

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#714]

**Comment by bess** [comment]
@shanitajohn I think this was fixed in our last release. Can you verify and close this ticket if it's no longer operative?

**Comment by mark-dce** [comment]
It's still occurring:
![#714 - Research Fields - Step 1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46abc3cb77c2cee9bdecac46a54ff39c69602e762500b06b3dc5d03cba523b504d435cec03070511afbd9b21b4b33424d9540dea846a0920956916acb8834eeb06bc74831997aaaec81d9ebc6278bec1da0d2c1417198ef55c30a1994cc85ff64ee24c5ca3017b.png)
![#714 - Research Fields - Step 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46abc3cb77c2cee9bdecac46a54ff39c69602e762500b06b3dc5d03cba523b534d435cec03070511afbd9b21b4b33424d9540dea846a0920956916acb8834eeb06bc74831997aaaec81d9ebc6278bec1da0d2c14171a89f55c30a1994cc85ff64ee24f54ad017b.png)
![#714 - Research Fields - Step 3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46abc3cb77c2cee9bdecac46a54ff39c69602e762500b06b3dc5d03cba523b524d435cec03070511afbd9b21b4b33424d9540dea846a0920956916acb8834eeb06bc74831997aaaec81d9ebc6278bec1da0d2c14171980f55c30a1994cc85ff64ee24f55a0017b.png)
![#714 - Research Fields - Step 4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46abc3cb77c2cee9bdecac46a54ff39c69602e762500b06b3dc5d03cba523b554d435cec03070511afbd9b21b4b33424d9540dea846a0920956916acb8834eeb06bc74831997aaaec81d9ebc6278bec1da0d2c1417198ef55c30a1994cc85ff64ee24f55a3017b.png)
![#714 - Research Fields - Step 5.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46abc3cb77c2cee9bdecac46a54ff39c69602e762500b06b3dc5d03cba523b544d435cec03070511afbd9b21b4b33424d9540dea846a0920956916acb8834eeb06bc74831997aaaec81d9ebc6278bec1da0d2c14171a89f55c30a1994cc85ff64ee24f56a2017b.png)
